=== skwak0205/GSC_RPMS/3dspace/webapps/ParameterizationSkeleton/assets/xml/DELConfigurationPropertiesView.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="ui">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="object" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="type" type="xs:string" />
            <xs:attribute name="id" type="xs:string" />
            <xs:attribute name="value" type="xs:string" />
            <xs:attribute name="disabled" type="xs:string" />
            <xs:attribute name="onChange" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nodetreenls" type="xs:string" />
      <xs:attribute name="treelistnls" type="xs:string" />
      <xs:attribute name="modalnls" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ui" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/ParameterizationSkeleton/assets/xml/RoleOnLinkLayoutTreeListViewArg.xml
<?xml version="1.0"?>
<!--<Result xsi:schemaLocation="DELConfigurationPropertiesView.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">-->
<ui nodetreenls="RoleOnLinkNodeTreeView" treelistnls="RoleOnLinkTreeListView" modalnls="RoleOnLinkModalView">
  <object type="textarea" id="attributeValue" value="" mandatory="true"></object>
  <object type="textarea" id="nbConsumption" value="" mandatory="true"></object>
  <object type="textarea" id="AF" value="" hidden="true"></object>
  <object type="textarea" id="AL" value="" hidden="true"></object>
  <object type="textarea" id="DZ" value="" hidden="true"></object>
  <object type="textarea" id="AS" value="" hidden="true"></object>
  <object type="textarea" id="AD" value="" hidden="true"></object>
  <object type="textarea" id="AO" value="" hidden="true"></object>
  <object type="textarea" id="AQ" value="" hidden="true"></object>
  <object type="textarea" id="AG" value="" hidden="true"></object>
  <object type="textarea" id="AR" value="" hidden="true"></object>
  <object type="textarea" id="AM" value="" hidden="true"></object>
  <object type="textarea" id="AW" value="" hidden="true"></object>
  <object type="textarea" id="AU" value="" hidden="true"></object>
  <object type="textarea" id="AT" value="" hidden="true"></object>
  <object type="textarea" id="AZ" value="" hidden="true"></object>
  <object type="textarea" id="BS" value="" hidden="true"></object>
  <object type="textarea" id="BH" value="" hidden="true"></object>
  <object type="textarea" id="BD" value="" hidden="true"></object>
  <object type="textarea" id="BB" value="" hidden="true"></object>
  <object type="textarea" id="BY" value="" hidden="true"></object>
  <object type="textarea" id="BE" value="" hidden="true"></object>
  <object type="textarea" id="BZ" value="" hidden="true"></object>
  <object type="textarea" id="BJ" value="" hidden="true"></object>
  <object type="textarea" id="BM" value="" hidden="true"></object>
  <object type="textarea" id="BT" value="" hidden="true"></object>
  <object type="textarea" id="BO" value="" hidden="true"></object>
  <object type="textarea" id="BA" value="" hidden="true"></object>
  <object type="textarea" id="BW" value="" hidden="true"></object>
  <object type="textarea" id="BV" value="" hidden="true"></object>
  <object type="textarea" id="BR" value="" hidden="true"></object>
  <object type="textarea" id="IO" value="" hidden="true"></object>
  <object type="textarea" id="BN" value="" hidden="true"></object>
  <object type="textarea" id="BG" value="" hidden="true"></object>
  <object type="textarea" id="BF" value="" hidden="true"></object>
  <object type="textarea" id="BI" value="" hidden="true"></object>
  <object type="textarea" id="KH" value="" hidden="true"></object>
  <object type="textarea" id="CM" value="" hidden="true"></object>
  <object type="textarea" id="CA" value="" hidden="true"></object>
  <object type="textarea" id="CV" value="" hidden="true"></object>
  <object type="textarea" id="KY" value="" hidden="true"></object>
  <object type="textarea" id="CF" value="" hidden="true"></object>
  <object type="textarea" id="TD" value="" hidden="true"></object>
  <object type="textarea" id="CL" value="" hidden="true"></object>
  <object type="textarea" id="CN" value="" hidden="true"></object>
  <object type="textarea" id="CX" value="" hidden="true"></object>
  <object type="textarea" id="CC" value="" hidden="true"></object>
  <object type="textarea" id="CO" value="" hidden="true"></object>
  <object type="textarea" id="KM" value="" hidden="true"></object>
  <object type="textarea" id="CG" value="" hidden="true"></object>
  <object type="textarea" id="CD" value="" hidden="true"></object>
  <object type="textarea" id="CK" value="" hidden="true"></object>
  <object type="textarea" id="CR" value="" hidden="true"></object>
  <object type="textarea" id="CI" value="" hidden="true"></object>
  <object type="textarea" id="HR" value="" hidden="true"></object>
  <object type="textarea" id="CU" value="" hidden="true"></object>
  <object type="textarea" id="CY" value="" hidden="true"></object>
  <object type="textarea" id="CZ" value="" hidden="true"></object>
  <object type="textarea" id="DK" value="" hidden="true"></object>
  <object type="textarea" id="DJ" value="" hidden="true"></object>
  <object type="textarea" id="DM" value="" hidden="true"></object>
  <object type="textarea" id="DO" value="" hidden="true"></object>
  <object type="textarea" id="EC" value="" hidden="true"></object>
  <object type="textarea" id="EG" value="" hidden="true"></object>
  <object type="textarea" id="SV" value="" hidden="true"></object>
  <object type="textarea" id="GQ" value="" hidden="true"></object>
  <object type="textarea" id="ER" value="" hidden="true"></object>
  <object type="textarea" id="EE" value="" hidden="true"></object>
  <object type="textarea" id="ET" value="" hidden="true"></object>
  <object type="textarea" id="FK" value="" hidden="true"></object>
  <object type="textarea" id="FO" value="" hidden="true"></object>
  <object type="textarea" id="FJ" value="" hidden="true"></object>
  <object type="textarea" id="FI" value="" hidden="true"></object>
  <object type="textarea" id="FR" value="" hidden="true"></object>
  <object type="textarea" id="GF" value="" hidden="true"></object>
  <object type="textarea" id="PF" value="" hidden="true"></object>
  <object type="textarea" id="TF" value="" hidden="true"></object>
  <object type="textarea" id="GA" value="" hidden="true"></object>
  <object type="textarea" id="GM" value="" hidden="true"></object>
  <object type="textarea" id="GE" value="" hidden="true"></object>
  <object type="textarea" id="DE" value="" hidden="true"></object>
  <object type="textarea" id="GH" value="" hidden="true"></object>
  <object type="textarea" id="GI" value="" hidden="true"></object>
  <object type="textarea" id="GR" value="" hidden="true"></object>
  <object type="textarea" id="GL" value="" hidden="true"></object>
  <object type="textarea" id="GD" value="" hidden="true"></object>
  <object type="textarea" id="GP" value="" hidden="true"></object>
  <object type="textarea" id="GU" value="" hidden="true"></object>
  <object type="textarea" id="GT" value="" hidden="true"></object>
  <object type="textarea" id="GN" value="" hidden="true"></object>
  <object type="textarea" id="GW" value="" hidden="true"></object>
  <object type="textarea" id="GY" value="" hidden="true"></object>
  <object type="textarea" id="HT" value="" hidden="true"></object>
  <object type="textarea" id="HM" value="" hidden="true"></object>
  <object type="textarea" id="HN" value="" hidden="true"></object>
  <object type="textarea" id="HK" value="" hidden="true"></object>
  <object type="textarea" id="HU" value="" hidden="true"></object>
  <object type="textarea" id="IS" value="" hidden="true"></object>
  <object type="textarea" id="IN" value="" hidden="true"></object>
  <object type="textarea" id="ID" value="" hidden="true"></object>
  <object type="textarea" id="IR" value="" hidden="true"></object>
  <object type="textarea" id="IE" value="" hidden="true"></object>
  <object type="textarea" id="IL" value="" hidden="true"></object>
  <object type="textarea" id="IT" value="" hidden="true"></object>
  <object type="textarea" id="JM" value="" hidden="true"></object>
  <object type="textarea" id="JP" value="" hidden="true"></object>
  <object type="textarea" id="JO" value="" hidden="true"></object>
  <object type="textarea" id="KZ" value="" hidden="true"></object>
  <object type="textarea" id="KE" value="" hidden="true"></object>
  <object type="textarea" id="KI" value="" hidden="true"></object>
  <object type="textarea" id="KP" value="" hidden="true"></object>
  <object type="textarea" id="KR" value="" hidden="true"></object>
  <object type="textarea" id="KW" value="" hidden="true"></object>
  <object type="textarea" id="KG" value="" hidden="true"></object>
  <object type="textarea" id="LA" value="" hidden="true"></object>
  <object type="textarea" id="LV" value="" hidden="true"></object>
  <object type="textarea" id="LB" value="" hidden="true"></object>
  <object type="textarea" id="LS" value="" hidden="true"></object>
  <object type="textarea" id="LR" value="" hidden="true"></object>
  <object type="textarea" id="LY" value="" hidden="true"></object>
  <object type="textarea" id="LI" value="" hidden="true"></object>
  <object type="textarea" id="LT" value="" hidden="true"></object>
  <object type="textarea" id="LU" value="" hidden="true"></object>
  <object type="textarea" id="MO" value="" hidden="true"></object>
  <object type="textarea" id="MK" value="" hidden="true"></object>
  <object type="textarea" id="MG" value="" hidden="true"></object>
  <object type="textarea" id="MW" value="" hidden="true"></object>
  <object type="textarea" id="MY" value="" hidden="true"></object>
  <object type="textarea" id="MV" value="" hidden="true"></object>
  <object type="textarea" id="ML" value="" hidden="true"></object>
  <object type="textarea" id="MT" value="" hidden="true"></object>
  <object type="textarea" id="MH" value="" hidden="true"></object>
  <object type="textarea" id="MQ" value="" hidden="true"></object>
  <object type="textarea" id="MR" value="" hidden="true"></object>
  <object type="textarea" id="MU" value="" hidden="true"></object>
  <object type="textarea" id="YT" value="" hidden="true"></object>
  <object type="textarea" id="MX" value="" hidden="true"></object>
  <object type="textarea" id="FM" value="" hidden="true"></object>
  <object type="textarea" id="MD" value="" hidden="true"></object>
  <object type="textarea" id="MN" value="" hidden="true"></object>
  <object type="textarea" id="MS" value="" hidden="true"></object>
  <object type="textarea" id="MA" value="" hidden="true"></object>
  <object type="textarea" id="MZ" value="" hidden="true"></object>
  <object type="textarea" id="MM" value="" hidden="true"></object>
