=== skwak0205/GSC_RPMS/3dspace/WEB-INF/classes/resources/param/DELPPWApplications/xsd/ColumnConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="dataIndex" use="required"/>
                <xs:attribute type="xs:string" name="dicoType" use="required"/>
                <xs:attribute type="xs:string" name="displayType" use="optional"/>
                <xs:attribute type="xs:string" name="minWidth" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Columns">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Column" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="dicoType" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="dicoType" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                      <xs:attribute type="xs:string" name="dataIndex" use="required"/>
                      <xs:attribute type="xs:boolean" name="display" use="optional"/>
                      <xs:attribute type="xs:string" name="dicoType" use="optional"/>
                      <xs:attribute type="xs:string" name="displayType" use="optional"/>
                      <xs:attribute type="xs:string" name="Tooltip" use="optional"/>
                      <xs:attribute type="xs:string" name="minWidth" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:string" name="Title"/>
      <xs:attribute type="xs:string" name="Description"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELMFNApp/assets/xml/ProcessColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Manufacturing" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
    <Columns>
        <Column dataIndex="PLM_ExternalID.instance" dicoType="DELFmiFunctionIdentifiedInstance"/>
        <Column dataIndex="revision.reference" displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="V_description.reference" dicoType="PLMEntity" Tooltip="NameRevisionOwner.tooltip"/>
        <Column dataIndex="V_ContQuantity.instance" displayType="MultiType" display="false">
            <dicoType dicoType="DELFmiContQuantity_Mass" />
            <dicoType dicoType="DELFmiContQuantity_Area" />
            <dicoType dicoType="DELFmiContQuantity_Length" />
            <dicoType dicoType="DELFmiContQuantity_Volume" />
        </Column>
        <Column dataIndex="DELFmiUseCaseExt.V_UseCase.instance" dicoType="DELFmiUseCaseExt" display="false"/>
        <Column dataIndex="V_TargetReleaseDate.reference" dicoType="DELFmiFunctionPPRCreateReference"/>
        <Column dataIndex="V_NeedDedicatedSystem.reference" dicoType="CreateAssembly"/>
        <Column dataIndex="ManufacturingItemUpdateStatus" displayType="BIEssentials"/>
        <Column dataIndex="AltSubBI" displayType="BIEssentialsAltSub"/>
       <!--  <Column dataIndex="DELFmiUseCaseExt.V_UseCase.instance" dicoType="DELFmiUseCaseExt"/> -->
        <Column dataIndex="current.reference"  displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="owner.reference"  displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="organization.reference" dicoType="BusinessType"/>
        <Column dataIndex="Scope.relation" displayType="Relation"/>
        <Column dataIndex="Implement.relation" displayType="Relation"/>
        <Column dataIndex="All.relation" displayType="Relation"/>
        <Column dataIndex="documents.document" displayType="DocMgmt"/>
        <Column dataIndex="V_isLastVersion.reference" dicoType="PLMCoreReference" displayType="NonEditable"/>
        <Column dataIndex="EnterpriseExtension.V_PartNumber.reference"  dicoType="EnterpriseExtension" displayType="URL"/>
        <!-- CONFIGURATION COLUMNS: start -->
        <Column dataIndex="ConfigurationContext" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="Effectivity" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="VariantEffectivity" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="CurrentEvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CHG role is valid -->
        <Column dataIndex="ProjectedEvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CHG role is valid -->
        <Column dataIndex="EvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CFG/CSV role is valid without CHG role -->
        <!-- CONFIGURATION COLUMNS: end -->
    </Columns>
</Config>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELMFNApp/assets/xml/ProductPartColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="ProductsAndParts" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label		dataIndex="V_Name.reference"		dicoType="PLMEntity"		displayType="NonEditable"/>
    <Columns>
        <Column dataIndex="PLM_ExternalID.instance"       dicoType="PLMCoreInstance"    displayType="NonEditable"  />
        <Column	dataIndex="revision.reference"		        dicoType="BusinessType"		    displayType="NonEditable"/>
        <Column dataIndex="ProductAssignmentStatus"       displayType="BIEssentials"/>
        <Column dataIndex="V_IsManufacturable.reference"       dicoType="VPMReference"  displayType="NonEditable"/>
        <Column dataIndex="AltSubBI"                      displayType="BIEssentialsAltSub"/>
        <Column	dataIndex="V_description.reference"	      dicoType="PLMEntity"		      displayType="NonEditable" Tooltip="NameRevisionOwner.tooltip"/>
        <Column	dataIndex="owner.reference"			          dicoType="BusinessType"		    displayType="NonEditable"/>
        <Column	dataIndex="PLM_ExternalID.reference"			dicoType="PLMEntity"		      displayType="NonEditable"/>
        <Column	dataIndex="V_isLastVersion.reference"			dicoType="PLMCoreReference"		displayType="NonEditable"/>
        <Column	dataIndex="current.reference"		          dicoType="BusinessType"		    displayType="NonEditable"/>
        <Column dataIndex="EnterpriseExtension.V_PartNumber.reference"  dicoType="EnterpriseExtension"                  displayType="NonEditable"/>
        <!-- CONFIGURATION COLUMNS: start -->
        <Column dataIndex="ConfigurationContext" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="Effectivity" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="VariantEffectivity" displayType="CFG" display="false"/><!-- Available if atleast CFG/CSV role is valid -->
        <Column dataIndex="CurrentEvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CHG role is valid -->
        <Column dataIndex="ProjectedEvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CHG role is valid -->
        <Column dataIndex="EvolutionEffectivity" displayType="CFG" display="false"/><!-- Available only if CFG/CSV role is valid without CHG role -->
        <!-- CONFIGURATION COLUMNS: end -->
    </Columns>
</Config>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELPPWFacets/assets/xml/ProcessColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Manufacturing" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label dataIndex="V_Name.reference" dicoType="PLMEntity" displayType="NonEditable"/>
    <Columns>
        <Column dataIndex="type.reference" displayType="CustomString"/>
        <Column dataIndex="V_Outsourced.reference" displayType="NonEditable"/>
        <Column dataIndex="revision.reference" displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="owner.reference"  displayType="FullOwnerURL" dicoType="BusinessType"/>
        <Column dataIndex="organization.reference" displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="project.reference"  displayType='URL'/>
        <Column dataIndex="current.reference"  displayType='URL' dicoType="BusinessType"/>
        <Column dataIndex="V_description.reference" dicoType="PLMEntity" displayType="NonEditable"/>
    </Columns>
</Config>
