=== skwak0205/GSC_RPMS/3dspace/WEB-INF/classes/resources/param/DELPPWApplications/xsd/GeneralPreferences.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Preferences">
          <xs:complexType>
            <xs:sequence>	  
			  <xs:element name="showCollaborativeSpace" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="showOrg" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="showRole" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="showDialog" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="oneDelmiaAggregationMode" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="fetchAllLevel" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="loadRootOnly" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="isReleaseMaturitySynced" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
              <xs:element name="isChangeRequiredSynced" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
			  <xs:element name="timeout">
			    <xs:complexType>
				  <xs:attribute name="defaultValue" type="xs:integer" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
				</xs:complexType>
              </xs:element>
			  <xs:element name="navigateOnIndex">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="tns:NavigateType" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
				  </xs:complexType>
              </xs:element>
			  <xs:element name="custoParametersSet">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:string" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
			  <xs:element name="separator">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="xs:string" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
				</xs:complexType>
              </xs:element>
			  <xs:element name="csvSeparator">
                <xs:complexType>
                  <xs:attribute name="defaultValue" type="tns:CSVSeparatorType" use="required"/>
				  <xs:attribute name="isVisible" type="xs:boolean" use="required"/>
				  <xs:attribute name="type" type="xs:string" use="required"/>
				</xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="Title" use="required"/>
      <xs:attribute type="xs:string" name="Description" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="NavigateType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Database"/>
      <xs:enumeration value="Index"/>
      <xs:enumeration value="IndexRelationsOnDemand"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CSVSeparatorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Comma"/>
      <xs:enumeration value="Semicolon"/>
      <xs:enumeration value="Pipe"/>
      <xs:enumeration value="Tab"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELMFNApp/assets/xml/GeneralPreferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/GeneralPreferences.xsd" Title="General preferences" Description="Sample configuration file delivered by DS.">
  <Preferences>
    <showCollaborativeSpace type="boolean" defaultValue="true" isVisible="true"/>
    <showOrg defaultValue="false" type="boolean" isVisible="true"/>
    <showRole defaultValue="false" type="boolean" isVisible="true"/>
    <showDialog defaultValue="true" type="boolean" isVisible="true"/>
    <oneDelmiaAggregationMode defaultValue="true" type="boolean" isVisible="true"/>
    <fetchAllLevel defaultValue="false" type="boolean" isVisible="true"/>
    <loadRootOnly defaultValue="true" type="boolean" isVisible="true"/>
    <isReleaseMaturitySynced defaultValue="false" type="boolean" isVisible="true"/>
    <isChangeRequiredSynced defaultValue="false" type="boolean" isVisible="true"/>
	<timeout defaultValue="600" type="text" isVisible="true" />
    <navigateOnIndex defaultValue="Index" type="list" isVisible="true" />
    <custoParametersSet defaultValue="OOTBValue" type="string" isVisible="true"/>
    <separator defaultValue="|" type="text" isVisible="true"/>
    <csvSeparator defaultValue="Comma" type="list" isVisible="true"/>
  </Preferences>
</Config>
