=== skwak0205/GSC_RPMS/3dspace/WEB-INF/classes/resources/param/DELPPWApplications/xsd/InsertCmdFormAttribute.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="AttributesDescriptionList">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Type" type="tns:Type"/>
      </xs:sequence>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Description" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Type">
    <xs:sequence>
    <xs:element maxOccurs="unbounded" name="Section" type="tns:Section"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="formStyle" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="Section">
    <xs:sequence>
    <xs:element maxOccurs="unbounded" name="Attribute" type="tns:Attribute"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="Attribute">
    <xs:sequence>
        <xs:element name="dicoType" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
            <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="dicoType" use="optional"/>
            </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="dicoType" type="xs:string"/>
    <xs:attribute name="entity" type="xs:string"/>
    <xs:attribute name="mandatory" type="xs:boolean"/>
    <xs:attribute name="displayType" type="xs:string"/>
    <xs:attribute name="defaultValue" type="xs:string"/>
  </xs:complexType>

</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELPPWComponentsFactory/assets/xml/InsertCmdFormAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2015 -->
<AttributesDescriptionList Title="Attributes Description List by Types" Description="Sample configuration file delivered by DS." xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/InsertCmdFormAttribute.xsd">
	<Type name="CreateAssembly">
		<Section name="Section.Attributes">
			<Attribute name="V_Name" dicoType="PLMEntity" mandatory="true" />
			<Attribute name="V_description" dicoType="PLMEntity" />
            <Attribute name="V_Outsourced" dicoType="CreateAssembly"/>
		</Section>
	</Type>
	<Type name="CreateMaterial">
		<Section name="Section.Attributes">
			<Attribute name="V_Name" dicoType="PLMEntity" mandatory="true" />
			<Attribute name="V_description" dicoType="PLMEntity" />
            <Attribute name="V_Outsourced" dicoType="CreateMaterial"/>
		</Section>
	</Type>
	<Type name="CreateKit">
		<Section name="Section.Attributes">
			<Attribute name="V_Name" dicoType="PLMEntity" mandatory="true" />
			<Attribute name="V_description" dicoType="PLMEntity" />
		</Section>
	</Type>
	<Type name="Provide">
		<Section name="Section.Attributes">
			<Attribute name="V_Name" dicoType="PLMEntity" mandatory="true" />
			<Attribute name="V_description" dicoType="PLMEntity" />
		</Section>
	</Type>
    <!--<Type name="ProcessContinuousProvide">
		<Section name="Section.Attributes">
			<Attribute name="V_Name" dicoType="PLMEntity" mandatory="true" />
			<Attribute name="V_description" dicoType="PLMEntity" />
            <Attribute name="V_ContQuantity" >
                <dicoType dicoType="DELFmiContQuantity_Mass" />
                <dicoType dicoType="DELFmiContQuantity_Area" />
                <dicoType dicoType="DELFmiContQuantity_Length" />
                <dicoType dicoType="DELFmiContQuantity_Volume" />
    	    </Attribute> 
		</Section>
	</Type>-->
</AttributesDescriptionList>
