=== skwak0205/GSC_RPMS/3dspace/WEB-INF/classes/resources/param/DELPPWApplications/xsd/RelationsColumnMapping.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<xs:simpleType name="directionValues">
  <xs:restriction base="xs:string">
    <xs:enumeration value="To" />
    <xs:enumeration value="From" />
    <xs:enumeration value="Both" />
  </xs:restriction>
 </xs:simpleType>
   <xs:element name="RelationsColumnMapping">
	<xs:complexType>
      <xs:sequence>
		  <xs:element name="RelationsColumns">
			<xs:complexType>
			  <xs:sequence>
				<xs:element name="RelationsColumn" maxOccurs="unbounded">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element name="LinkedObjectConstraint" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
						  <xs:sequence>
							<xs:element name="Attribute" maxOccurs="unbounded" minOccurs="0">
							  <xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
							  </xs:complexType>
							</xs:element>
						  </xs:sequence>
						  <xs:attribute name="dicoType" type="xs:string" use="required"/>
						</xs:complexType>
					  </xs:element>
					  <xs:element name="Relation" maxOccurs="unbounded">
						<xs:complexType>
						  <xs:attribute name="name" type="xs:string" use="required"/>
						  <xs:attribute name="attribute_source" type="xs:string" use="required"/>
						  <xs:attribute name="direction" type="tns:directionValues" use="required"/>
						</xs:complexType>
					  </xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required"/>
				  </xs:complexType>
				</xs:element>
			  </xs:sequence>
			  <xs:attribute name="Title" type="xs:string" use="optional"/>
			  <xs:attribute name="Description" type="xs:string" use="optional"/>
			</xs:complexType>
		  </xs:element>
		  <xs:element name="RelationsDisplayAttributes">
			<xs:complexType>
			  <xs:sequence>
				<xs:element name="Type"  maxOccurs="unbounded" minOccurs="0">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element name="Attribute" maxOccurs="unbounded" minOccurs="0">
						<xs:complexType>
						  <xs:attribute name="name" type="xs:string" use="required"/>
						</xs:complexType>
					  </xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="display_icon" type="xs:string"/>
					<xs:attribute name="separator" type="xs:string"/>
				  </xs:complexType>
				</xs:element>
				<xs:element name="Relation"  maxOccurs="unbounded" minOccurs="0">
				  <xs:complexType>
					<xs:sequence>
					  <xs:element name="Attribute" maxOccurs="unbounded" minOccurs="0">
						<xs:complexType>
						  <xs:attribute name="name" type="xs:string" use="required"/>
						</xs:complexType>
					  </xs:element>
					</xs:sequence>
					<xs:attribute name="linkName" type="xs:string" use="required"/>				
					<xs:attribute name="display_icon" type="xs:string"/>
					<xs:attribute name="separator" type="xs:string"/>
				  </xs:complexType>
				</xs:element>
			  </xs:sequence>
			  <xs:attribute name="Title" type="xs:string" use="optional"/>
			  <xs:attribute name="Description" type="xs:string" use="optional"/>
			</xs:complexType>
		  </xs:element>
	  </xs:sequence>
	  <xs:attribute name="Title" type="xs:string" use="optional"/>
      <xs:attribute name="Description" type="xs:string" use="optional"/>
    </xs:complexType>
   </xs:element>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELMFNApp/assets/xml/RelationsColumnMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<RelationsColumnMapping xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/RelationsColumnMapping.xsd" Title="Relations columns configuration" Description="Sample configuration file delivered by DS.">
  <RelationsColumns>
      <RelationsColumn name="Scope.relation">
        <Relation name="ProcessImplementLink" attribute_source="Type" direction="To"/>
        <Relation name="ProductImplementLink" attribute_source="Type" direction="To"/>
        <Relation name="PartialProductImplementLink" attribute_source="Type" direction="To"/>
      </RelationsColumn>
      <RelationsColumn name="Implement.relation">
        <Relation name="ProductImplementLinkOcc" attribute_source="Type" direction="To"/>
      </RelationsColumn>
      <RelationsColumn name="Alternate.relation">
        <Relation name="MfgProcessAlternate" attribute_source="Type" direction="To"/>
      </RelationsColumn>
      <RelationsColumn name="AlternateOf.relation">
        <Relation name="MfgProcessAlternate" attribute_source="Type" direction="From"/>
      </RelationsColumn>
      <RelationsColumn name="Origin.relation">
        <Relation name="HistorizationLinkRefRef" attribute_source="Type" direction="To"/>
      </RelationsColumn>
      <RelationsColumn name="OriginOf.relation">
        <Relation name="HistorizationLinkRefRef" attribute_source="Type" direction="From"/>
      </RelationsColumn>
      <RelationsColumn name="All.relation">
        <Relation name="ProcessImplementLink" attribute_source="Type" direction="To"/>
        <Relation name="ProductImplementLink" attribute_source="Type" direction="To"/>
        <Relation name="ProductImplementLinkOcc" attribute_source="Type" direction="To"/>
        <Relation name="DELLmiProductionSystemOutputCnxToMBOM" attribute_source="Type" direction="To"/>
        <Relation name="DELAsmProcessCanUseCnx" attribute_source="Type" direction="To"/>
        <Relation name="HistorizationLinkRefRef" attribute_source="Type" direction="To"/>
        <Relation name="MfgProcessAlternate" attribute_source="Type" direction="To"/>
        <Relation name="PartialProductImplementLink" attribute_source="Type" direction="To"/>
      </RelationsColumn>
  </RelationsColumns>
  <RelationsDisplayAttributes>
      <Type name="DELLmiGeneralSystemReference" display_icon="relation">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELSCPLogisticsSiteRef" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiTransformationSystemReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiWorkPlanSystemReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiTransferSystemReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="SourceSystem" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="SinkSystem" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="BufferSystem" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiGeneralOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiPunctualOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiCurveOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiLoadingOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiUnloadingOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiTransferOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiRemoveMaterialOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="DELLmiHeaderOperationReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="CreateAssembly" display_icon="relatedObject">
          <Attribute name="V_Name" />
          <Attribute name="revision" />
      </Type>
      <Type name="Part" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="Provide" display_icon="relatedObject">
          <Attribute name="V_Name" />
      </Type>
      <Type name="VPMReference" display_icon="relatedObject">
          <Attribute name="V_Name" />
          <Attribute name="revision" />
      </Type>
      <Type name="VPMInstance" display_icon="relatedObject">
          <Attribute name="PLM_ExternalID" />
      </Type>
  </RelationsDisplayAttributes>
</RelationsColumnMapping>
