=== skwak0205/GSC_RPMS/properties/resources/param/DELPPWApplications/xsd/IndexMapping.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="IndexMapping">
    <xs:complexType>
      <xs:all>
        <xs:element name="Relation" type="tns:IndexMappingType" minOccurs="0"/>
        <xs:element name="Entity" type="tns:IndexMappingType" minOccurs="0"/>
      </xs:all>
      <xs:attribute name="Title" type="xs:string" use="required" />
      <xs:attribute name="Description" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="IndexMappingType">
    <xs:sequence>
      <xs:element name="Key" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="index" type="xs:string" use="required"/>
          <xs:attribute name="database" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELPPWComponentsFactory/assets/xml/IndexMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<!--	Mapping between index names and database names -->
<IndexMapping xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/IndexMapping.xsd" Title="Mapping between index names and database names" Description="Sample configuration file delivered by DS.">
  <Relation>
    <Key index="physicalid"                                  database="PID"/>
    <Key index="type"                                        database="type"/>
    <Key index="ro.plminstance.plm_externalid"               database="PLM_ExternalID"/>
    <Key index="ro.plminstance.v_treeorder"                  database="V_TreeOrder"/>
    <Key index="ro.DELLmiOperationPPRInstance.V_Balanceable" database="V_Balanceable"/>
    <Key index="from.physicalid"                             database="isAggregatedBy"/>
    <Key index="to.physicalid"                               database="isInstanceOf"/>
  </Relation>
  <Entity>
    <Key index="physicalid"                                  database="PID"/>
    <Key index="type"                                        database="type"/>
    <Key index="name"                                        database="PLM_ExternalID"/>
    <Key index="ds6w:label"                                  database="V_Name"/>
    <Key index="bo.PLMEntity.V_description"                  database="V_description"/>
    <Key index="bo.PLMEntity.V_discipline"                   database="V_discipline"/>
    <Key index="bo.Resource.V_MTBF"                          database="V_MTBF"/>
    <Key index="bo.Robot.V_DELRmi_MountingMethod"            database="V_DELRmi_MountingMethod"/>
    <Key index="bo.Robot.V_DELRmi_NbDOFs"                    database="V_DELRmi_NbDOFs"/>
    <Key index="current"                                     database="current"/>
    <Key index="revision"                                    database="revision"/>
    <Key index="owner"                                       database="owner"/>
    <Key index="interface"                                   database="interface"/>
    <Key index="organization"                                database="organization"/>
    <Key index="bo.PLMReference.V_isLastVersion"             database="V_isLastVersion"/>
    <Key index="bo.PLMReference.V_TargetReleaseDate"         database="V_TargetReleaseDate"/>
    <Key index="bo.CreateAssembly.V_NeedDedicatedSystem"     database="V_NeedDedicatedSystem"/>
    <Key index="bo.DELAsmProcessCanUseCnx.V_ResourcesQuantity" database="V_ResourcesQuantity"/>

    <Key index="resourceid"                                  database="resourceid"/>
    <Key index="ds6w:what/ds6w:type"                         database="type"/>

    <Key index="DELSysSpecificationLinksDiscipline"          database="SystemImplementLink"/>
    <Key index="MfgProductionPlanning"                       database="ProcessImplementLink"/>
    <Key index="DELFmiProcessImplementCnx"                   database="ProductImplementLink"/>
    <Key index="ds6w:kind"                                   database="V_usage"/>
  </Entity>
</IndexMapping>
