=== skwak0205/GSC_RPMS/properties/resources/param/DELPPWApplications/xsd/ProductFlowViewReferenceAttribute.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Preferences">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Node">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Lines" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="Line" >
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="Info">
                                  <xs:complexType>
                                    <xs:attribute name="property" type="xs:string" use="required"/>
                                    <xs:attribute name="dicoType" type="xs:string"/>
                                    <xs:attribute name="maxWidth" type="xs:string"/>
                                    <xs:attribute name="fontSize" type="xs:string"/>
                                    <xs:attribute name="fontWeight" type="xs:string"/>
                                    <xs:attribute name="color" type="xs:string"/>
                                    <xs:attribute name="displayAttributeName" type="xs:boolean"/>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Image">
                <xs:complexType>
                  <xs:attribute name="value" type="xs:boolean" use="required"/>
                </xs:complexType>
              </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Link">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Info">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="dicoType" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Description" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/webapps/DELPPWProductFlowFacet/assets/xml/ProductFlowViewReferenceAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ProductFlowViewReferenceAttribute.xsd" Title="GraphView reference attributes preferences" Description="Sample configuration file delivered by DS.">
	<Preferences>
		<Node>
			<Lines>
				<Line>
					<Info property="V_Name" fontSize="20px" fontWeight="bold" color="#77797c" maxWidth="70%" />
					<Info property="revision" dicoType="BusinessType" fontSize="20px" color="#77797c" />
				</Line>
				<Line>
					<Info property="PLM_ExternalID" dicoType="DELFmiFunctionIdentifiedInstance" fontSize="12px"  color="#77797c" />
				</Line>
				<Line>
					<Info property="V_EstimatedTime" dicoType="DELLmiOperationReference" fontSize="12px" color="#b4b6ba" displayAttributeName="true" />
				</Line>
			</Lines>
			<Image value="true"/>
		</Node>
		<Link>
			<Info name="type"></Info>
		</Link>
	</Preferences>
</Config>
