=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- please do not change a single char in this file without notifying PPN. thnks -->
  
  <xs:complexType name="sourceType">
    <xs:sequence>
      <xs:element type="targetType" name="target" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" 		name="name"		use="required"/>
    <xs:attribute type="sourceTypeType" name="type" 	use="required"/>
    <xs:attribute type="partExtensionType" name="partExtension" use="optional"/> <!-- for eCAD, only applies to 'Part' -->
    <xs:attribute type="subTypeType" 	name="subtype" 	use="optional"/> <!-- for eCAD, only applies to 'Part', but used also for 'Document' -->
   </xs:complexType>
 
<!--  list of possible values for the type attr of a source -->
<xs:simpleType name="sourceTypeType">
  <xs:restriction base="xs:string">
    <!-- Start with the IRPC types of 3DSpace -->
    <xs:enumeration value="Part"/>
    <xs:enumeration value="IPart"/>       <!-- IPART is used by Inventor for Part and iPart -->
    <xs:enumeration value="SEComponent"/> <!-- SEComponent is used by SolidEdge for Part and SheetMetal -->
    <xs:enumeration value="Drawing"/>
    <xs:enumeration value="3DShape"/>
    <xs:enumeration value="SIMShape"/>
	<xs:enumeration value="Material"/>
    <xs:enumeration value="Assembly"/>
    <xs:enumeration value="Analysis"/>
    <xs:enumeration value="Process"/>
    <xs:enumeration value="CREOPart"/>
	<!-- below one matches for CVS Document (ER model) of 3DSpace -->
    <xs:enumeration value="Document"/>
    <!-- Temporary addition for CATIAV5 Converter, should be managed by subType-->
    <xs:enumeration value="CATShape"/>
    <xs:enumeration value="Model"/>
    <xs:enumeration value="cgr"/>
  </xs:restriction>
</xs:simpleType>   

<!--  list of possible values for the partExtension attr of a source -->
<xs:simpleType name="partExtensionType">
  <xs:restriction base="xs:string">
    <!-- subtypes of Part for eCAD -->
    <xs:enumeration value="CBDBoard"/>               <!-- Printed Circuit Board -->
    <xs:enumeration value="PLMPCBPackageFootprint"/> <!-- Footprint -->
    <xs:enumeration value="PLMPCBPackageWrap"/>      <!-- PackageWrap -->
 </xs:restriction>
</xs:simpleType>   

 <!--  list of possible values for the subtypes attr of a source -->
<xs:simpleType name="subTypeType">
  <xs:restriction base="xs:string">
    <!-- subtypes of Part for eCAD -->
    <xs:enumeration value="CBDBoard"/>               <!-- Printed Circuit Board -->
    <xs:enumeration value="PLMPCBPackageFootprint"/> <!-- Footprint -->
    <xs:enumeration value="PLMPCBPackageWrap"/>      <!-- PackageWrap -->
   <!-- subtypes of Part for CV5 -->
    <xs:enumeration value="CATShape"/>
    <xs:enumeration value="model"/>
    <xs:enumeration value="cgr"/>
	<!-- subtypes of Document , only Office Doc for now-->
    <xs:enumeration value="config"/>
	<!-- subtypes of Document , only Office Doc for now-->
    <xs:enumeration value="WordProcessed"/>
    <xs:enumeration value="Spreadsheet"/>
    <xs:enumeration value="Presentation"/>
    <xs:enumeration value="email"/>
    <xs:enumeration value="CSV"/>
 	<!-- subtypes of Document , for Image -->
    <xs:enumeration value="raster"/>
    <xs:enumeration value="vectorial"/>
 </xs:restriction>
</xs:simpleType>   
 
  <xs:complexType name="targetType" mixed="true">
    <xs:sequence>
      <xs:element type="parameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name"           type="xs:string"          use="required" />
	<xs:attribute name="inputStreamId"  type="inputstreamIdType"  use="required" />
    <xs:attribute name="outputStreamId" type="outputstreamIdType" use="required" />
    <xs:attribute name="downloadable"   type="xs:boolean"         use="optional" default="true"/>
    <xs:attribute name="conversionService" type="xs:boolean"      use="optional" default="false"/>
    <xs:attribute name="cloudOnly"      type="xs:boolean"         use="optional" default="false"/>
  </xs:complexType>
  
  <xs:complexType name="parameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="values" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="range" use="optional"/>  <!-- only for int/double/numerical value...not et supported -->
        <xs:attribute type="xs:string" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
        <xs:attribute type="xs:boolean" name="mandatory" use="optional"/> <!-- default is False if not present -->
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  
<!--  list of possible values for INPUT streamId -->
<xs:simpleType name="inputstreamIdType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="authoring"/>
    <xs:enumeration value="authoringvisu"/>
    <xs:enumeration value="linkable"/>
	<!-- cases with 'DO' prefix means the input in in a stream of DerivedOutputEntity -->
    <xs:enumeration value="DWG"/>
    <xs:enumeration value="DXF"/>
    <xs:enumeration value="STEP"/> <!-- formats may be stp, step, stpZ -->
	</xs:restriction>
</xs:simpleType>

<!--  list of possible values for OUTPUT streamId -->
<xs:simpleType name="outputstreamIdType">
  <xs:restriction base="xs:string">
	<!-- first formats for internal DS (not downloadable) -->
	<xs:enumeration value="authoringvisu"/> <!-- CGR, UDL, and ConvService is using 'vizualisation' for 3DXML/UDL -->
	<xs:enumeration value="linkable"/>
	<xs:enumeration value="catiav5"/>
	<xs:enumeration value="XCADPivot"/>
	<xs:enumeration value="acis_powerby"/>
	<xs:enumeration value="visualization"/>
	<!-- and below formats for exchange -->
	<xs:enumeration value="STEP"/>
	<xs:enumeration value="STEP_AP203"/>
	<xs:enumeration value="STEP_AP214"/>
	<xs:enumeration value="STEP_AP242"/>
	<xs:enumeration value="PDF"/>
	<xs:enumeration value="PDF/A"/>
	<xs:enumeration value="TIF"/>
	<xs:enumeration value="DWG"/>
	<xs:enumeration value="DWF"/>
	<xs:enumeration value="DXF"/>
	<xs:enumeration value="CGR"/>
	<xs:enumeration value="cgrv5"/>  <!-- light version of catiav5, only tesselation-->
	<xs:enumeration value="HCG"/>
	<xs:enumeration value="MODEL"/>
	<xs:enumeration value="SVG"/>
	<xs:enumeration value="PNG"/>    <!-- PNG includes PNG and BMP, aka lossless raster images -->
	<xs:enumeration value="CGM"/>
	<xs:enumeration value="PS"/>     <!--PostScript-->
	<xs:enumeration value="JPG"/>
	<xs:enumeration value="GIF"/>
	<xs:enumeration value="IG2"/>
	<xs:enumeration value="GL2"/>
	<xs:enumeration value="VPS"/>
	<xs:enumeration value="STL"/>
	<xs:enumeration value="IGES"/>
	<xs:enumeration value="WRL"/>
	<xs:enumeration value="3DMAP"/>
	<xs:enumeration value="3DXML"/>
	<xs:enumeration value="CATALOG"/>
	<!-- GEOVIA SURPAC from 23xFD01 -->
	<xs:enumeration value="SDM"/>
	<!-- XCV from 23xFD01 -->
	<xs:enumeration value="XCV"/>
	<!-- special * value is used when the outputStreamId is computed from amndatory attributes -->
	<xs:enumeration value="*"/>
	<!-- Non DS supported cases: Elysium, TSystems,... -->
	<xs:enumeration value="XVL"/>
	<xs:enumeration value="ICAD"/>
	<xs:enumeration value="PRT"/>
	<xs:enumeration value="NX"/>
	<xs:enumeration value="CREO"/>
	<xs:enumeration value="JT"/>

  </xs:restriction>
</xs:simpleType>   
  
  <xs:complexType name="eventType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="eventNameType" name="name" use="required"/>
        <xs:attribute type="eventTypeType" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="maturityGraph" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
 
<!--  list of supported event name -->
<xs:simpleType name="eventNameType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="checkin"/>
    <xs:enumeration value="promote"/>
    <xs:enumeration value="demote"/>
    <xs:enumeration value="ondemand"/>
    <xs:enumeration value="onXCADSave"/>
  </xs:restriction>
</xs:simpleType> 
  
 <!--  list of supported event type -->
<xs:simpleType name="eventTypeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Trigger"/>
    <xs:enumeration value="interactiveUpdate"/>
	
  </xs:restriction>
</xs:simpleType>   

  <xs:complexType name="eventsType">
    <xs:sequence>
      <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- each CAD supports a list of data, and a list of event . ultimately, the list of event should be 'independant' from CAD-->
  <xs:complexType name="datasourceType">
    <xs:sequence>
      <xs:element type="sourceType" name="source" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="eventsType" name="events" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="dataSourceNameType" name="name" use="required"/>
  </xs:complexType>
  
   <!--  list of supported "CAD" -->
    <xs:simpleType name="dataSourceNameType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="3DEXPERIENCE"/>
        <xs:enumeration value="CATIAV5"/>
        <xs:enumeration value="SOLIDWORKS"/>
        <xs:enumeration value="CREO"/>
        <xs:enumeration value="NX"/>
        <xs:enumeration value="INVENTOR"/>
        <xs:enumeration value="SOLIDEDGE"/>
        <xs:enumeration value="AUTOCAD"/>
        <xs:enumeration value="DRAFTSIGHT"/>
        <!-- CAD supported by Elysium -->
        <xs:enumeration value="ICAD"/>
        <!-- OC only from 22XFD01 -->
        <xs:enumeration value="MicrosoftOffice"/>
        <!-- and now ECAD, from 22XFD04 -->
        <xs:enumeration value="CADENCEALLEGRO"/>
        <xs:enumeration value="ALTIUM"/>
        <xs:enumeration value="CADENCEPULSE"/>
        <xs:enumeration value="ZUKENDSCR"/>
        <xs:enumeration value="XPEDITIONEDM"/>
        <!-- GEOVIA, from 23XFD01 -->
        <xs:enumeration value="SURPAC"/>
        <!-- Image, from 23XFD02 -->
        <xs:enumeration value="Image"/>
		<!-- REVIT, from 23xFD01 -->
        <xs:enumeration value="REVIT"/>
      </xs:restriction>
    </xs:simpleType> 

  
  <!-- each converter may manage different CAD -->
  <xs:complexType name="datasourcesType">
    <xs:sequence>
      <xs:element type="datasourceType" name="datasource" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- Converter : use different files for different converters, they are then agregated-->
  <xs:complexType name="converterType">
    <xs:sequence>
      <xs:element type="datasourcesType" name="datasources" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="converterNameType" name="name" use="required"/>
    <xs:attribute type="xs:string" name="nlsFile" use="required"/>
    <xs:attribute type="xs:boolean" name="synchronous" use="required"/>
    <xs:attribute type="xs:string" name="comment" use="optional"/>
  </xs:complexType>
 
    <!--  list of supported converterNameType -->
    <xs:simpleType name="converterNameType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="3DEXPERIENCE"/>
        <xs:enumeration value="CATIAV5"/>
        <xs:enumeration value="SOLIDWORKS"/>
        <xs:enumeration value="CREO"/>
        <xs:enumeration value="NX"/>
        <xs:enumeration value="Inventor"/>
        <xs:enumeration value="SolidEdge"/>
        <xs:enumeration value="AutoCAD"/>
        <xs:enumeration value="Elysium"/>
        <xs:enumeration value="ODC"/>
      </xs:restriction>
    </xs:simpleType> 

 
  <!-- root level of dDerivedouputDeclarative*.xml files -->
  <xs:complexType name="derivedformatmanagementType">
    <xs:sequence>
      <xs:element type="converterType" name="converter" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="derivedformatmanagement" type="derivedformatmanagementType"/>
  
</xs:schema>

=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_CATIAV5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
    <!-- first official version for 22xFD2, from CHOUDHARI Ashwini ' proposal in Jan 2022  -->
	<converter name="CATIAV5" synchronous="true"  nlsFile="emxDerivedFormatManagementCATIAV5StringResource" comment="conversion managed synchronously at save by XCAD">
      <datasources>
		<datasource name="CATIAV5" >    <!-- XCAD CATIA V5 only manages the CATIA V5 DataSource -->
			<source name="CATPart" type ="Part">
				<target name="cgr"   inputStreamId="authoring" outputStreamId="CGR" />
				<target name="hcg"   inputStreamId="authoring" outputStreamId="HCG" />
				<target name="iges"  inputStreamId="authoring" outputStreamId="IGES" />
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="model" inputStreamId="authoring" outputStreamId="MODEL" />
				<target name="png"   inputStreamId="authoring" outputStreamId="PNG" />
				<target name="postscript" inputStreamId="authoring" outputStreamId="PS" /> 
				<target name="step"  inputStreamId="authoring" outputStreamId="*" > <!-- need to refine with application Level : 203 214 242 -->
					<parameter name="ApplicationProtocol" values="AP203|AP203E2|AP214|AP214E3|AP242E1|AP242E2"  type="enum" default="AP242E1" mandatory="true"/>
				</target>
				<target name="stl"   inputStreamId="authoring" outputStreamId="STL" />
				<target name="svg"   inputStreamId="authoring" outputStreamId="SVG" />
				<target name="vps"   inputStreamId="authoring" outputStreamId="VPS" />
				<target name="wrl"   inputStreamId="authoring" outputStreamId="WRL" />
				<target name="3dmap" inputStreamId="authoring" outputStreamId="3DMAP" />
				<target name="3dxml" inputStreamId="authoring" outputStreamId="3DXML" />
			</source>
			
			<source name="CATDrawing" type ="Drawing">
				<target name="catalog" inputStreamId="authoring" outputStreamId="CATALOG" />
				<target name="cgm"   inputStreamId="authoring" outputStreamId="CGM" />
				<target name="dwg"   inputStreamId="authoring" outputStreamId="DWG" />
				<target name="gl2"   inputStreamId="authoring" outputStreamId="GL2"/>
				<target name="ig2"   inputStreamId="authoring" outputStreamId="IG2"/>
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="pdf"   inputStreamId="authoring" outputStreamId="PDF"/>
				<target name="png"   inputStreamId="authoring" outputStreamId="PNG"/>
				<target name="postscript" inputStreamId="authoring" outputStreamId="PS" />
				<target name="svg"   inputStreamId="authoring" outputStreamId="SVG" />
				<target name="dxf"   inputStreamId="authoring" outputStreamId="DXF" />
				<target name="tif"   inputStreamId="authoring"  outputStreamId="TIF"/>
				<target name="3dxml" inputStreamId="authoring" outputStreamId="3DXML" />
			</source>
			
			<source name="MODEL" type="Model" subtype="model" >
				<target name="cgr"   inputStreamId="authoring" outputStreamId="CGR" />
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="png"   inputStreamId="authoring"  outputStreamId="PNG"/>			
			</source>
			
			<source name="CATAnalysis" type="Analysis">
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="png"        inputStreamId="authoring" outputStreamId="PNG" />
			</source>

			<source name="CATShape" type="CATShape" subtype="CATShape">
				<target name="cgr"   inputStreamId="authoring" outputStreamId="CGR" />
				<target name="iges" inputStreamId="authoring" outputStreamId="IGES" />
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="model" inputStreamId="authoring"  outputStreamId="MODEL"/>
				<target name="png"   inputStreamId="authoring"  outputStreamId="PNG"/>
				<target name="postscript" inputStreamId="authoring"  outputStreamId="PS"/>
				<target name="step"  inputStreamId="authoring" outputStreamId="*" > <!-- need to refine with application Level : 203 214 242 -->
					<parameter name="ApplicationProtocol" values="AP203|AP203E2|AP214|AP214E3|AP242E1|AP242E2"  type="enum" default="AP242E1" mandatory="true"/>
				</target>

				<target name="stl"   inputStreamId="authoring"  outputStreamId="STL"/>
				<target name="tif"   inputStreamId="authoring"  outputStreamId="TIF"/>
				<target name="wrl"   inputStreamId="authoring"  outputStreamId="WRL"/>
				<target name="3dmap" inputStreamId="authoring"  outputStreamId="3DMAP"/>
			</source>

			<source name="CGR" type="cgr" subtype="cgr">
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="png"        inputStreamId="authoring" outputStreamId="PNG" />
			</source>
			
			<source name="CATProcess" type="Process">
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="png"        inputStreamId="authoring" outputStreamId="PNG" />
				<target name="3dxml"      inputStreamId="authoring" outputStreamId="3DXML" />
			</source>

			<source name="CATMaterial" type="Material">
				<target name="image_jpeg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="png"        inputStreamId="authoring" outputStreamId="PNG" />
			</source>

			<events>        <!-- XCAD CATIA V5 only manages the case of save from CATIA V5 -->
				<event name="onXCADSave" type="interactiveUpdate" />
			</events>
		</datasource>
	  </datasources>
	</converter>

</derivedformatmanagement>

=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_CREO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
    <!-- first official version for R2023x Beta2 and R2022x FD04  -->
	<converter name="CREO" synchronous="true"  nlsFile="emxDerivedFormatManagementCREOStringResource" comment="conversion managed synchronously at save by CREO PowerBy connector">
      <datasources>
		<datasource name="CREO" >    
			<source name="PRT,XPR" type ="CREOPart">
				<target name="image_jpg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="tif"       inputStreamId="authoring" outputStreamId="TIF" />
				<target name="iges"      inputStreamId="authoring" outputStreamId="IGES"/>
				<target name="png"       inputStreamId="authoring" outputStreamId="PNG"/>
				<target name="step"      inputStreamId="authoring" outputStreamId="STEP" />
			</source>
					
			<source name="DRW" type ="Drawing">
				<target name="image_jpg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="postscript" inputStreamId="authoring" outputStreamId="PS" />
				<target name="dxf"      inputStreamId="authoring" outputStreamId="DXF"/>
				<target name="iges"     inputStreamId="authoring" outputStreamId="IGES"/>
				<target name="cgm"      inputStreamId="authoring" outputStreamId="CGM"/>				
				<target name="pdf"      inputStreamId="authoring" outputStreamId="PDF"/>
				<target name="dwg"      inputStreamId="authoring" outputStreamId="DWG"/>
			</source>
			
			<events>       
				<event name="onXCADSave" type="interactiveUpdate" />
			</events>
		</datasource>
	  </datasources>
	</converter>

</derivedformatmanagement>

=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_NX.xml
<?xml version="1.0" encoding="UTF-8" ?>
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
    <!-- first official version for R2023x Beta2 and R2022x FD04  -->
	<converter name="NX" synchronous="true"  nlsFile="emxDerivedFormatManagementNXStringResource" comment="conversion managed synchronously at save by NX PowerBy connector">
      <datasources>
		<datasource name="NX" >    
			<source name="PRT" type ="Part">
				<target name="image_jpg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="tif" 		inputStreamId="authoring" outputStreamId="TIF" />
				<target name="gif" 		inputStreamId="authoring" outputStreamId="GIF" />
				<target name="iges" 	inputStreamId="authoring" outputStreamId="IGES"/>
				<target name="png" 		inputStreamId="authoring" outputStreamId="PNG"/>
				<target name="step"   	inputStreamId="authoring" outputStreamId="STEP" />
			</source>
					
			<source name="PRT" type ="Drawing">
				<target name="image_jpg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="cgm" 		inputStreamId="authoring" outputStreamId="CGM"/>				
				<target name="iges" 	inputStreamId="authoring" outputStreamId="IGES"/>
				<target name="pdf"  	inputStreamId="authoring" outputStreamId="PDF"/>
				<target name="dwg" 		inputStreamId="authoring" outputStreamId="DWG"/>
			</source>
			
			<events>       
				<event name="onXCADSave" type="interactiveUpdate" />
			</events>
		</datasource>
	  </datasources>
	</converter>

</derivedformatmanagement>

=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_Inventor.xml
<?xml version="1.0" encoding="UTF-8" ?>
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
    <!-- first official version for R2023x Beta2 and R2022x FD04  -->
	<converter name="Inventor" synchronous="true"  nlsFile="emxDerivedFormatManagementInventorStringResource" comment="conversion managed synchronously at save by Inventor PowerBy connector">
      <datasources>
		<datasource name="INVENTOR" >    
			<source name="IPT" type ="IPart">  <!-- IPART here is a keyword specific to Inventor, look at this key in nlsFile file -->
				<target name="preview"  inputStreamId="authoring" outputStreamId="PNG" />
				<target name="dwf"      inputStreamId="authoring" outputStreamId="DWF" />
				<target name="step203"  inputStreamId="authoring" outputStreamId="STEP_AP203"/>
				<target name="step214"  inputStreamId="authoring" outputStreamId="STEP_AP214"/>
				<target name="pdf"      inputStreamId="authoring" outputStreamId="PDF" />
			</source>
					
			<source name="IDW,DWG" type ="Drawing">
				<target name="preview"  inputStreamId="authoring" outputStreamId="PNG" />
				<target name="dwf"      inputStreamId="authoring" outputStreamId="DWF" />
				<target name="pdf"      inputStreamId="authoring" outputStreamId="PDF" />
			</source>
	
			<events>       
				<event name="onXCADSave" type="interactiveUpdate" />
			</events>
		</datasource>
	  </datasources>
	</converter>

</derivedformatmanagement>

=== skwak0205/GSC_RPMS/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_AutoCAD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
    <!-- first official version for R2023x Beta2 and R2022x FD04  -->
	<converter name="AutoCAD" synchronous="true"  nlsFile="emxDerivedFormatManagementAutoCADStringResource" comment="conversion managed synchronously at save by AutoCAD PowerBy connector">
      <datasources>
		<datasource name="AUTOCAD" >    
			<source name="DWG" type ="Drawing">
				<target name="pdf"      inputStreamId="authoring" outputStreamId="PDF" />
				<target name="image_jpg" inputStreamId="authoring" outputStreamId="JPG" />
				<target name="dxf"      inputStreamId="authoring" outputStreamId="DXF" />
				<target name="dwf"      inputStreamId="authoring" outputStreamId="DWF" />
				<target name="stl"      inputStreamId="authoring" outputStreamId="STL" />
			</source>
	
			<events>       
				<event name="onXCADSave" type="interactiveUpdate" />
			</events>
		</datasource>
	  </datasources>
	</converter>

</derivedformatmanagement>
